# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
    - run: npm ci
    - name: Building
    - run: npm run build
    - name: upload executable windows
      if: ${{runner.os == 'Windows'}} 
      uses: actions/upload-artifact@v3
      with:
        name: client-win.exe
        path: ./build/client-win.exe
    - run: ls
    - name: upload executable linux
      if: ${{runner.os == 'Linux'}} 
      uses: actions/upload-artifact@v3
      with:
        name: client-linux
        path: ./build/client-linux
